name: 'dbt_artifacts'
version: '0.1.0'
config-version: 2
require-dbt-version: ">=0.19.0"

vars:
  full_exec_filter: '1=1'

models:
  dbt_artifacts:
    # No schema override is defined here, but we recommend that you
    # override the schema for specific projects.
    +materialized: table
    incremental:
      +materialized: incremental
    staging:
      +materialized: view # The staging tables cannot be ephemeral
